# -*- coding: utf-8 -*-
"""implementation of central tendancy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMZh2tfrqPhkZclihr9GgQ7bNi7bbcm_
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
df=pd.read_csv("bmi.csv")
df

x=df["Height"].mean()

x

plt.scatter(x, '*')
plt.show()

df.mean()

df["Height"].median()

df.median()

df["Height"].mode()

df.mode()

df["Height"].var()

df["Height"].std()

df.std()

m1=df["Height"].max()
m1
m2=df["Height"].max()
m2
range=m1-m2
range

import numpy as np
import pandas as pd
import seaborn as sns

sns.boxplot(x="Height",data=df)

sns.boxplot(x="Weight",data=df)

sns.boxplot(x="Index",data=df)

